### ISSUE TITLE
Roadmap 2022 

### ISSUE THREAD

**Issue by zhangyangyu** [tidb-incubator/TiBigData#134]
This is TiBigData roadmap 2022.

It's under iterative edition and we welcome everyone to make advice.

# Features

## Flink

- [ ] Fast Lookup with PK & Secondary Indices
- [ ] Support Pre Split & Auto Random & Auto Increment when batch load
- [ ] Support Upsert & Delete DML
- [ ] Unified Batch & Streaming Processing
- [ ] Support Catalog
- [ ] Support External Connector Interface
- [ ] Support FDW integration and Cloud EMR integration
- [ ] Support Async Query

## Spark (we'd like to merge TiSpark into TiBigData)

- [ ] Support Pre Split & Auto Random & Auto Increment when batch load
- [ ] Support Upsert & Delete DML
- [ ] Unified Batch & Streaming Processing
- [ ] Support Catalog
- [ ] Support External Connector Interface
- [ ] Support FDW integration and Cloud EMR integration
- [ ] Support Async Query

# Quality

- [ ] Establish GA criteria

**Comment by humengyu2012** [comment]
What's the Async Query?

**Comment by sunxiaoguang** [comment]
> What's the Async Query?

It's about using FDW to submit asynchronous query to Spark / Flink from TiDB directly.

**Comment by gbzy** [comment]
It's important to support tikv native writing, the writing speed is  the bottleneck of flink batch job.

**Comment by sunxiaoguang** [comment]
> It's important to support tikv native writing, the writing speed is the bottleneck of flink batch job.

This particular feature is what you want
- Support Upsert & Delete DML
